### ISSUE TITLE
Consider Relaxing Node Version

### ISSUE THREAD

**Issue by hbetts** [svnlto/local-or-home-npmrc#4]
Please consider relaxing the version range for Node in the `engines` property of your `package.json` file to allow for Node version 4.

For Yarn users, a `yarn install` will fail if the user's current version of Node does not match the Node version range within a package's `engine` property of their `package.json` file - https://github.com/yarnpkg/rfcs/pull/69#issuecomment-308567694

I recently brought this up to a downstream consumer, `npm-utils` - bahmutov/npm-utils#45

Looking through the `index.js` file, I don't see any ES6+ features that would fail on Node 4.

The `test.js` file, though it has arrow functions, will still work on Node 4, and it actually doesn't really matter for that file, as you're using `ava`, which handles transpiling of your code for you.

**Comment by svnlto** [comment]
Done

**Comment by hbetts** [comment]
Closing as this issue was address by #3
